# Generated by Django 5.2.4 on 2025-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField()),
                ('params', models.JSONField()),
                ('device_info', models.JSONField()),
                ('location', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
