# Generated by Django 5.2.4 on 2025-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbehaviorlog',
            old_name='request_time',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='userbehaviorlog',
            name='sequence_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
