# Generated by Django 5.2.4 on 2025-09-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_rename_request_time_userbehaviorlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehaviorlog',
            name='is_processed_by_ml',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('anomaly_score', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('behavior_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_results', to='behavior.userbehaviorlog')),
            ],
        ),
    ]
