# Generated by Django 5.2.4 on 2025-09-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_userbehaviorlog_is_processed_by_ml_anomalyresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehaviorlog',
            name='is_processed_by_ml',
        ),
        migrations.DeleteModel(
            name='AnomalyResult',
        ),
    ]
