# Generated by Django 5.2.4 on 2025-07-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('decision', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('behavior_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behavior.userbehaviorlog')),
            ],
        ),
    ]
