# Generated by Django 5.2.4 on 2025-08-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalyresult',
            old_name='confidence',
            new_name='anomaly_score',
        ),
        migrations.RemoveField(
            model_name='anomalyresult',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='anomalyresult',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='anomalyresult',
            name='is_anomaly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anomalyresult',
            name='modality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anomalyresult',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
