# Generated by Django 5.2.4 on 2025-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly', '0002_rename_confidence_anomalyresult_anomaly_score_and_more'),
        ('behavior', '0004_remove_userbehaviorlog_is_processed_by_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyresult',
            name='detection_method',
            field=models.CharField(choices=[('iforest', 'IsolationForest'), ('lstm', 'LSTM'), ('hybrid', 'Hybrid')], db_index=True, default='hybrid', help_text='Anomaly detected by: iForest, LSTM, iForest+LSTM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='anomalyresult',
            index=models.Index(fields=['modality'], name='anomaly_ano_modalit_b88ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyresult',
            index=models.Index(fields=['timestamp'], name='anomaly_ano_timesta_2e45b6_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyresult',
            index=models.Index(fields=['created_at'], name='anomaly_ano_created_e584bd_idx'),
        ),
    ]
